### ISSUE TITLE
Output CSV using API

### ISSUE THREAD

**Issue by InTheScript** [harvesthq/api#100]
Hi there,

I'm trying to get a full harvest_time_report output as a CSV over the API. It looks like there is an endpoint for this (see below). But it doesn't seem to be accepting HTTP basic Auth.

https://<SUBDOMAIN>.harvestapp.com/exports/<ID>

I basically need to be able to get the full CSV programmatically output at a regular cadence to a remote server.

Hope this is possible.

Best,
Mulenga

**Comment by lanej0** [comment]
Hi, sorry we don't have a documented method for outputting anything other than XML or JSON data via the API.
