### ISSUE TITLE
Harvest Python API Wrapper by Lann does not seem to be remotely functional.

### ISSUE THREAD

**Issue by mekhami** [harvesthq/api#102]
Consider removing this from your list as I have had no success in trying to get it to perform any basic functions.  The examples have incorrect syntax, there's no real documentation, the library itself didn't install out of the box, running the code after I fix the syntax throws only 404 errors...

Safe to say this wrapper is defunct.

**Comment by lanej0** [comment]
Last update was 16 hours ago (albeit it was a minor one).  So I'm hesitant to remove this because it looks like there is some activity on the repository.

**Comment by mekhami** [comment]
The last update was literally me trying to fix their broken script just so I could install the thing with pip..

**Comment by lanej0** [comment]
I should have dug in further.  I'll remove the reference for now (not like we can't put it back if work resumes!)
