### ISSUE TITLE
Return status code of 303 when there is a location header in a response 

### ISSUE THREAD

**Issue by lrdiv** [harvesthq/api#103]
Currently, when POSTing to an endpoint like `/clients/` a status code of 201 is returned, but a location header is passed with a URL for the endpoint that contains the data for the created record.

Many REST clients (I'm using restler for node) won't follow this redirect unless the status code is 3xx. I believe that 303 is the appropriate status code in this case.

**Comment by lanej0** [comment]
We're giving the standard Rails response of a 201 combined with a Location header for POST requests.  I surveyed our dev team, and nobody has ever seen a 303 response in an API POST request.  Are you aware of anyone who's doing this?

**Comment by lrdiv** [comment]
@lanej0 I haven't seen it in the wild, my suggestion is based on this wikipedia entry: http://en.wikipedia.org/wiki/HTTP_303

> The HTTP response status code 303 See Other is a way to redirect web applications to a new URI, particularly after an HTTP POST has been performed

I understand not wanting to change the response codes in an API of this size, I just ran into this issue recently and thought it would be worth suggesting. Thanks for the response!
