### ISSUE TITLE
Wrong HTTP status codes used 

### ISSUE THREAD

**Issue by timwhitlock** [harvesthq/api#110]
Seeing as my issue #109 was closed so eagerly, I'll report this as a bug.

The API often returns misleading status codes. Permission Denied issues should not return 404. It makes it impossible for developers to debug their integrations.

**Comment by destroytoday** [comment]
+1 - I came across this problem, too. The status code should be 403 Forbidden.

**Comment by AaronHolbrook** [comment]
Ha, maybe that's what I'm seeing in #128

**Comment by mitch000001** [comment]
+1 for proper status codes. Also it would be nice to document the error response:
If you get a 404 because of missing authorization there is a X-404 header included which tells you why it was not found.

**Comment by lanej0** [comment]
Coming in API v2!
