### ISSUE TITLE
What encoding does Harvest use for /projects names?

### ISSUE THREAD

**Issue by secrettriangle** [harvesthq/api#111]
We're receiving `\xe8` as part of the name which doesn't decode to `utf8`. Looks like `latin-1`. Can you confirm?

**Comment by lanej0** [comment]
As a general rule, we use UTF-8 across the board for things.  

![screen shot 2015-03-30 at 7 31 09 am](https://cloud.githubusercontent.com/assets/80276/6898391/dee03e32-d6ae-11e4-9b33-068d29f3c72e.png)

Not sure where \xe8 is coming from.  I did a test on my end, and just receive back the character:

![screen shot 2015-03-30 at 7 35 41 am](https://cloud.githubusercontent.com/assets/80276/6898514/817006e6-d6af-11e4-832f-0269e066cfcb.png)

**Comment by secrettriangle** [comment]
Confirmed, thanks!
