### ISSUE TITLE
Time entries filtered by task id

### ISSUE THREAD

**Issue by mitch000001** [harvesthq/api#112]
Hi,
Is it possible to add a filter query param to filter time entries by task_id?
So a call would look like: 
GET /projects/#{project_id}/entries?task_id=1334
With that the client is not forced to filter the tasks by hand.

Best,
Michael

**Comment by lanej0** [comment]
Hi Michael, 

It's not currently possible to do this, but I'll tag it as a requested enhancement.  

Jon

**Comment by mitch000001** [comment]
Hey Jon,

Thank you. This will ease the use very much.

Michael
