### ISSUE TITLE
Access integration data via Time Tracking API

### ISSUE THREAD

**Issue by brianlittmann** [harvesthq/api#118]
Hey guys, thoughts on having the ability to get/set 3rd-party integration links on a time entry? For example, when tracking time through the [Basecamp Chrome extension](https://www.getharvest.com/basecamp), the entry's `notes` is linked to the Basecamp to-do. However, I don't see a way to get that link in the [docs](https://github.com/harvesthq/api/blob/master/Sections/Time%20Tracking.md).

**Comment by lanej0** [comment]
Hey!

You're talking about external_ref: https://github.com/harvesthq/api/issues/64

Currently that's only available through Harvest Platform integrations, and is read only in the Harvest API.  I believe that that info is available from /daily and in the reporting API.

Does that help?

**Comment by brianlittmann** [comment]
Rad, the Harvest Platform is actually perfect. And I promise I tried searching the issues first before posting! Thanks for the quick reply. Keep up the good work!

**Comment by lanej0** [comment]
You would have had no idea to search for external_ref (who comes up with these names?)

Glad that helped :-)
