### ISSUE TITLE
/Projects returns content-type 'application/json' when requesting 'application/xml'

### ISSUE THREAD

**Issue by marioharper** [harvesthq/api#120]
Requesting /projects:

The contents of the response are in xml format, however, the header has an application type of application/json.

**Comment by lanej0** [comment]
Thanks for reporting that!  I'm seeing it too.  I'll get an issue opened up with our development team and we'll get that fixed up.

**Comment by lanej0** [comment]
This has been fixed and deployed.  I checked on my end and the header looks okay now, let me know if you see any further issues!

**Comment by marioharper** [comment]
Thanks!

**Comment by hbgwhite** [comment]
Thank you!
