### ISSUE TITLE
Add support for '?slim=1' on the '/daily' endpoints for 'application/json'

### ISSUE THREAD

**Issue by r0adkll** [harvesthq/api#121]
I've noticed that when using `?slim=1` on the `/daily` endpoints that it provides a faster/leaner response but only when using `application/xml` for the Accept header. Would you provide support for the JSON accept type? This would be extremely helpful for the application I'm currently working on.

**Comment by lanej0** [comment]
@jisraelsen What do you think?  Is this a quick addition?

**Comment by jisraelsen** [comment]
I'm not sure how quick it would be, but I'm on board for us adding it to keep things consistent.

**Comment by lanej0** [comment]
Created an internal ticket for this enhancement!

**Comment by r0adkll** [comment]
Thanks guys!

**Comment by lanej0** [comment]
This is out there now! Let us know if you run into any issues.

**Comment by r0adkll** [comment]
Awesome!! Thanks!
