### ISSUE TITLE
day_entry responses inconsistent

### ISSUE THREAD

**Issue by FlorianLudwig** [harvesthq/api#124]
The api is inconsistent regarding the contents of day_entry responses:

/people/#{user_id}/entries does not contain external_ref

/daily/#{day_of_the_year}/#{year} does not contain is_billed

/daily/show/#{day_entry_id} does not contain is_billed

**Comment by lanej0** [comment]
Those are different endpoints serving different purposes -- one is part of the time tracking API, the other is a part of our reporting API.  Just as the various reports in Harvest all show different types of information, we're okay with having the different sections show different information.

**Comment by FlorianLudwig** [comment]
I try to create a script to do reporting based on trello cards which is not possible via the provided gui.  Therefor I need to sync all entries.  The most efficient way (for us and your server) is using the updated_since parameter.  This is only possible using the reporting api.  Also we need external_ref as well as is_billed.

The only solution I came up with so far: Do one request per user to the reporting API and then one for every day with changed entries to get the external_ref and correlate the results.

This is as intended and okay?

(which sadly does not solve the problem that the referenced trello card cannot be changed afterwards, neither per gui/chrome plugin nor via api)
