### ISSUE TITLE
401 when attempting to query project entries

### ISSUE THREAD

**Issue by bbrock25** [harvesthq/api#126]
401 Response Code on all queries listed here on [project entries](https://github.com/harvesthq/api/blob/master/Sections/Time%20and%20Expense%20Reporting.md)

I don't believe that this is an authentication issue as I have been able to make requests to many of the other endpoints within the api with the same user/session.

I also wanted to mention that I am using the methods described [here](https://github.com/harvesthq/api/blob/master/Authentication/OAuth%202.0.md)   OAuth 2.0

**Comment by lanej0** [comment]
Probably best to write in to support for that they can take a look at the error logs on your account. There's no API-wide outage.

**Comment by bbrock25** [comment]
Thanks!

**Comment by asymmetric** [comment]
Same here, I can query other endpoints but get a 401 on `/entries` and `/expenses`. Seems to be a [common issue](https://github.com/zenhob/hcl/issues/15#issuecomment-31107174) too.

Plz reopen? :heart:

**Comment by lanej0** [comment]
It's common, but it's because of accounts with insufficient privileges and things like that.  It's not an issue with the API or API docs.  Getting in touch with our support team is the quickest way to track down why you're seeing the issue.
