### ISSUE TITLE
GET /people api request returns 404

### ISSUE THREAD

**Issue by AaronHolbrook** [harvesthq/api#128]
I'm able to successfully list things like /projects, but /people returns 404. 

I've tried listing a single person (myself) and just the plain list, but all returns 404. Does not indicate auth or any other issues.

**Comment by AaronHolbrook** [comment]
I believe this is related to #110, but would like confirmation that is the case from someone at Harvest

**Comment by lanej0** [comment]
Most likely that's what you're seeing.  /people is only accessible to an administrator through the API.  Guessing you're not authenticated with an admin account?

**Comment by schnetthappens** [comment]
Hey @lanej0, I'm experiencing the same issue as @AaronHolbrook. However, I am authenticated with an admin account. The GET request doesn't return a 404 in my case, rather a successful 200 request. 

I did some digging, and it looks like the AJAX call is hitting the correct endpoint, but then getting automatically redirected to some other URL. 

Specifically, this is when I'm attempting to GET all time entries logged by a user for a given timeframe (only trying to GET my own time entries).

**Comment by schnetthappens** [comment]
I'm having trouble sending any successful GET requests to any of the endpoints that must include the `entries?from=YYYYMMDD&to=YYYYMMDD` syntax.

**Comment by lanej0** [comment]
There isn't a bug, I just confirmed that it's working on my test account.

Might be easiest just to write in to support with the specifics of the request you're sending and what you're getting back (response code as well as error message).  We can check through the logs on our end and figure out what's going wrong specifically.
