### ISSUE TITLE
Include project code in day entries

### ISSUE THREAD

**Issue by kostajh** [harvesthq/api#131]
If I call `/daily`, the project code for a project shows up in the list of possible values one can clock in for (i.e. it's in the `projects` list), but it's not in the list of items that one has already clocked in for during the day (`day_entries`). Would it be possible to include that field in the `day_entries` section of the `/daily` feed?

**Comment by lanej0** [comment]
@jisraelsen what do you think?

**Comment by jisraelsen** [comment]
I don't think it should be a problem.
