### ISSUE TITLE
Filtering Invoices by kind

### ISSUE THREAD

**Issue by wjarka** [harvesthq/api#134]
It would be very useful for me if I could query the API to get all of the invoices of one kind "free_form" for example. Or at least, to have "kind" included in the results, so I could filter it on my side of the integration. 

The goal is to get a list of free_form invoices for a given period. 

Thanks!

**Comment by lanej0** [comment]
This is definitely an enhancement.

You can get what you need currently, but it's a bit tricky to do.  You'd have to retrieve all invoices for a period of time, and then grab each one individually (/invoices/#number).  If the invoice has ```<csv-line-items>```, it's a free form invoice
