### ISSUE TITLE
HTTP400 On Token Request

### ISSUE THREAD

**Issue by earlesja** [harvesthq/api#136]
Following the "Server Side" OAuth2.0 Guide: https://github.com/harvesthq/api/blob/master/Authentication/OAuth%202.0.md
I am able to request a code, and it shows up appropriately at my redirect_uri - however, whenever I then post the auth code back to Harvest, I receive a 400 Error.

**Request:**
*https://[platform].harvestapp.com/oauth2/token?grant_type=authorization_code&client_id=[obfuscated]&client_secret=[obfuscated]&code=[obfuscated]&redirect_uri=[obfuscated]*
**Content-Type:** *application/x-www-form-urlencoded*

Error:
>*{
"error": "invalid_grant",
"error_description": "The provided access grant is invalid, expired, or revoked (e.g. invalid assertion, expired authorization token, bad end-user password credentials, or mismatching authorization code and redirection URI)."
}*

[This makes some sense when using PostMan/DHC I suppose, since maybe a failed attempt to authenticate revokes the token? But I've now implemented the same attempt at the server level, with the same results.]

Just to make sure I had the right approach, I have also tried posting the contents of the URL above as the contents of the POST as a JSON string.

Thanks for any suggestions. I do not have a ticket open with Harvest, because I am not sure where the problem lies.

**Comment by lanej0** [comment]
Hey Jonathan,

It's probably best to open a support ticket with us on this.  That way we can check into the logs for your account and see what we're getting from you/why we're sending you back an error.  

I can say that the whole token request/response flow isn't broken -- it's in use by several integrations, so there must be something account/request specific going on here.

What you're describing sounds right (in terms of what you're doing) but something is going astray somewhere along the way!

Jon
