### ISSUE TITLE
Allow port in return_uri

### ISSUE THREAD

**Issue by holmboe** [harvesthq/api#137]
I am writing a command line tool and would like to avoid resorting to HTTP Basic Authentication. I have tried to use out-of-band workflow but it is currently not supported, see #75. So I thought to try embedding a short-lived webserver in my tool. It is a little cumbersome but doable.

However, it seems that I cannot define a custom port to the `redirect_uri` parameter, that is, other than port 80 which is the default when nothing is defined.

```python
from sanction.client import Client
import webbrowser
c = Client(
    auth_endpoint=AUTH_ENDPOINT,
    client_id=CLIENT_ID,
    client_secret=CLIENT_SECRET,
)
webbrowser.open(
    c.auth_uri(
        redirect_uri=REDIRECT_URI,
        state=CSRF_TOKEN,
    )
)
```

I recieve "Invalid Authorization Request Invalid redirect_uri is given" from your API server.

The effect is that I cannot think of a solution to allow a regular user to execute the tool as they would not have permissions to bind port 80. Please advise.

**Comment by lanej0** [comment]
@holmboe I can open an issue on this for you.  In the meantime, a workaround that I found out on the web is to use a URL shortener like bit.ly.  Put in http://127.0.0.1:XXXX and you'll receive a shortened URL that doesn't need the port specified.

Hope that helps!

**Comment by holmboe** [comment]
Why was this issue closed?

**Comment by lanej0** [comment]
Because it's a feature request for the API (which I've forwarded to the dev team).  This repo is for API documentation -- and there's nothing to document here!

**Comment by holmboe** [comment]
@lanej0 Thanks for clarifying.
