### ISSUE TITLE
[Question] How do I get unquie id from Client Dashboard using api?

### ISSUE THREAD

**Issue by anorsich** [harvesthq/api#139]
Hi,
At the moment I can get client_key from any invoice, go to public invoice page and extract link to the client's dashboard from "See All Invoices" link. This is a bit tricky and it would be nice to load unique id for client's dashboard via api (as part of client object for example).

Am I missed something in the api docs?

Thank you for the all your work.

**Comment by lanej0** [comment]
@jisraelsen do we expose the "Client dashboard" key anywhere that you know of.  /invoices gives a client-key but that's invoice specific.  Any way you know of to retrieve the key for the dashboard (/client/statements/{the key})?

**Comment by jisraelsen** [comment]
@lanej0 There isn't any way of getting the client's `statement_key` (that's used in the client dashboard URL) from the API.

It looks like we used to include it in the `GET /client/:id` response.  However, [we removed it a couple years ago](https://github.com/harvesthq/harvestapp/pull/1736) because it wasn't documented or needed.

**Comment by anorsich** [comment]
@lanej0 / @jisraelsen Thank you for getting back to me. 
If `statement_key` can be included into client api - that would be nice. 
My company use harvest to manage time, invoices and payments. We've build custom time reports using harvest api, but still would like to include link to harvest page where all invoices and payments listed. That's why we would like to get `statement_key` for any given client. In fact I've got this link using simple crawler, but it is not very nice solution.

**Comment by jisraelsen** [comment]
@anorsich We just made a small release adding `statement_key` back to the Client API!  It should show up in responses from both `GET /clients` and `GET /client/:id`.

**Comment by anorsich** [comment]
@jisraelsen Thank you.
Keep it up!
