### ISSUE TITLE
Not all project data from the website is accessible trough https://xxxx.harvestapp.com/projects

### ISSUE THREAD

**Issue by TobieDk** [harvesthq/api#140]
Hi guys

Would be nice if you can add this information in https://xxxxx.harvestapp.com/projects response

money_budget: null
money_budget_graph_percentage: null
money_budget_left: null
money_budget_left_percentage: null
money_budget_spent: null
money_budget_spent_percentage: null
over_money_budget: null
total_cost: 0

All of the above is a part of the API used on the website API ( https://xxxxx.harvestapp.com/projects/detailed?ids=xxxxx%2Cxxxxxx ), hope they can be added?

Btw. Another feature i'll love you add, is the option to filter active and inactive projects on https://xxxxx.harvestapp.com/projects (i only need a list of our active projects)

**Comment by lanej0** [comment]
I'll label this as an enhancement/feature request and get this added into our queue.
