### ISSUE TITLE
Testing / Sandbox mode?

### ISSUE THREAD

**Issue by bww** [harvesthq/api#141]
Maybe I've overlooked something in the documentation, but I don't see any way to use this API in testing mode. Is there no way to interact with this API without actually affecting real data? Generally services that deal in important things (like money) provide some sort of sandbox mechanism for testing against that insulates you from the possibility of inadvertently affecting real, live data.

**Comment by lanej0** [comment]
We've always suggested that folks sign up a trial account for all of their API testing needs.  If it takes you longer than 30 days to develop what you're working on, just drop our support team a line, and they'll happily extend the trial period for you.
