### ISSUE TITLE
Deleting an entry gives a 404

### ISSUE THREAD

**Issue by marol87** [harvesthq/api#143]
From angular.js I'm doing the http call:
$http.post('/daily/delete/', { entriesArray: $scope.entriesArray }))

on the node.js side I'm doing
harvest.TimeTracking.delete(entriesArray[1], function(err, res){
    console.log(err, res);
});

this gives me "{ status: '404', error: 'Not Found' } {}", 

any idea why?

**Comment by lanej0** [comment]
A 404 with the Harvest API could be an authentication issue (only an administrator or the "owner" of the time entry can delete it).

Another thing I noticed is that it looks like you're sending a POST request.  To remove an entry, you should send a DELETE (I don't think that would result in a 404 though).  If that's not it, drop us a line in support so we can take a look at the logs on your account and see what we're actually receiving.

**Comment by marol87** [comment]
I've tried changing the request to a DELETE but in that way I have no way of sending any request data that in this case consists of an array of entries that I want to delete. Here's a more detailed description of what I've done:

I'm using the Node.js library and this is the code for deleting a time entry

https://github.com/log0ymxm/node-harvest/blob/master/lib/time-tracking.js#L74

As you can see the library makes an delete request and the url seems to be fine.

for example
( /daily/delete/382707741 )

From angular.js I'm doing the this http call which is linked to a button:

$scope.deleteTime = function(){

$http.post('/daily/delete', { entriesArray: $scope.entriesArray })

.then(function(response){

console.log(response);

if(response.data == "ok"){

console.log("Deleted time entries");

}

}, function(response){

console.log("error", response);

});

};

on the node.js side I'm doing

router.post('/daily/delete', function(req, res) {

var harvest = new Harvest(req.session.user);

var entriesArray = req.body.entriesArray;

harvest.TimeTracking.delete(entriesArray[1], function(err, res){

console.log("Err");

console.log(err, res);

});

res.send("ok");

});

this gives me "{ status: '404', error: 'Not Found' } {}",

**Comment by lanej0** [comment]
Your best bet is probably to write in to support so that we can check out the logs on your account and see what we're receiving from you.
