### ISSUE TITLE
array indexes are not supported

### ISSUE THREAD

**Issue by G3z** [harvesthq/api#144]
this querystring is valid (invoices):
`from=20150101&to=20151231&status[0]=open&status[1]=paid&page=2`
but the api ignores the status parameter while this works:
`from=20150101&to=20151231&status[]=open&status[]=paid&page=2`
i think there is some problem parsing the querystring

**Comment by lanej0** [comment]
Using an array of values isn't something we currently support.  Your best bet is to send separate calls for each status you're trying to retrieve.
