### ISSUE TITLE
Find deleted time entries

### ISSUE THREAD

**Issue by kvarga** [harvesthq/api#146]
If someone deletes a time entry, there is no way to determine this in the API it appears.

Is there a way to add a way to find recently deleted time entries?

**Comment by lanej0** [comment]
https://github.com/harvesthq/api/issues/88

Once something is deleted, it's gone.  We don't keep a placeholder or have a way to retrieve it.

**Comment by kvarga** [comment]
Where should feature requests be logged? Ideally there would be a table that API users could query to get this information, or not actually deleting the record in the system and using a tombstone/deleted flag on the record itself.

**Comment by lanej0** [comment]
Best to write in to support with feature requests.
