### ISSUE TITLE
Project API documents needs to be updated to reflect new "project-type" field

### ISSUE THREAD

**Issue by ryancastle** [harvesthq/api#147]
Projects seem to have a new compulsory field, which isn't yet documented.

**Comment by lanej0** [comment]
Where are you seeing a "project-type" field?  I've just checked both our JSON and XML endpoints and didn't receive it in either response.

**Comment by ryancastle** [comment]
It's actually related to the beta projects feature we signed up for, so documenting it is probably premature.
