### ISSUE TITLE
POST request to /client to create client doesn't return newly created client id

### ISSUE THREAD

**Issue by bilalnaeem** [harvesthq/api#148]
Hi, I am using Harvest API and creating client via access_token. When I send post request  to 

   
         https://xyz.harvestapp.com/clients?access_token=xudfdfd 

with data like 

       {"client":{"name":"New Client"}}

And here is my CURL code

     $headers = array(
            "Content-type: application/json",
            "Accept: application/json",
        );

        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, $uri);
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
        curl_setopt($ch,CURLOPT_USERAGENT,'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.17 (KHTML, like Gecko) Chrome/24.0.1312.52 Safari/537.17');
        curl_setopt($ch, CURLOPT_AUTOREFERER, true);
        curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
        curl_setopt($ch, CURLOPT_VERBOSE, 1);
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($data));

        $response = curl_exec($ch);

And 

        
           var_dump($response);die; 
prints

       string ' ' (length=1)

Client is created but It donesn't send back newly created client id. How can I get client_id of newly created client?

**Comment by lanej0** [comment]
It should send the ID back in a header called Location. Are you seeing that returned?

**Comment by bilalnaeem** [comment]
Hi, 
Just curious to know why it is sent in Location? I have not experienced any thing like it. All create call usually send newly created id or whole objects? Why you are sending it in that way?

**Comment by lanej0** [comment]
Because it sends the location (URL) of the newly created client.  It's not uncommon when doing POSTs to handle it this way.

**Comment by bilalnaeem** [comment]
And if I need that newly created object. Then I need to make another get request to retrieve that object. 
Don't you think it is a bad idea as you people also enforce request limit in 15 seconds too?

**Comment by lanej0** [comment]
The request limit is on the same request multiple times within the same 15 second period.  Throttling requests so that the same report (for example) requested multiple times isn't at all uncommon.  The majority of APIs available have some sort of request throttling in place to prevent abuse.
