### ISSUE TITLE
'Get time entries from project and timeframe' returns inaccurate billable status

### ISSUE THREAD

**Issue by stevenbennett** [harvesthq/api#152]
Results from GET `/projects/#{project_id}/entries?from=YYYYMMDD&to=YYYYMMDD&user_id=#{user_id}` show billable and non-billable entries, but both types have the 'billable' status set to 'true'.

Adding the parameter `&billable=no` returns the correct entries, but the 'billable' status for each entry is still set to 'true'.

It would be useful to have accurate 'billable' statuses when requesting `/projects/#{project_id}/entries?from=YYYYMMDD&to=YYYYMMDD&user_id=#{user_id}` so that non-billable entries can be filtered from the results without making another request. It also seems like all of the entries returned using the  `&billable=no` parameter should have 'billable' set to false.

**Comment by lanej0** [comment]
Are you referring to ```<is-billed>```?  That indicates whether an entry has been invoiced or not, not whether it is billable or not.  We don't return the billable status of an entry in that particular call -- billable status is set at the project/task level.

**Comment by kostajh** [comment]
@lanej0 All I know is that prior to 12/31, I was able to make an API call to `/projects/{project_id}/entries` and have a field called `billable` which indicated if the time entry was billable or not. After 12/31 that was no longer present. I was using this [here](https://github.com/savaslabs/sumac/commit/1dfa5079f037b9b1299d859c317f460f28d2ed93).

**Comment by lanej0** [comment]
Merge this into https://github.com/harvesthq/api/issues/152
