### ISSUE TITLE
Data format changed for project entries

### ISSUE THREAD

**Issue by kostajh** [harvesthq/api#153]
There used to be a field called `billable` on entries retrieved from `/project/{id}/entries`. Some time around 12/31, it is no longer present in the data. I noticed that the field isn't listed [here](https://github.com/harvesthq/api/blob/master/Sections/Time%20and%20Expense%20Reporting.md#get-all-time-entries-logged-to-a-project-for-a-given-timeframe), but maybe you will consider adding it back? It's quite useful.

**Comment by lanej0** [comment]
Okay, so the gist is that we're making changes to projects right now.  Back in November, a few columns were exposed in the API that weren't ready for primetime (https://github.com/harvesthq/api/issues/152 alludes to this... accurate information wasn't being returned).  Around the end of December, we realized these were exposed and suppressed them again.

Billable may be making a comeback in the future as we continue to work on reporting in Harvest, it just wasn't ready yet.
