### ISSUE TITLE
Expense Categories Update Bug

### ISSUE THREAD

**Issue by ithielnor** [harvesthq/api#81]
If I PUT the following to /expense_categories/#{id}

```
<expense-category>
  <name>Updated Expense Category</name>
</expense-category>
```

Harvest updates the name, but also removes any configured unit-name and unit-price. I don't think it should do so.

Incidentally, the following xml functions as expected (leaves the name intact):

```
<expense-category>
  <unit-name>TEST</unit-name>
  <unit-price>0</unit-price>
</expense-category>
```

Finally, I noticed that unit-name and unit-price seem to be interdependent. You can't have one without the other. If this is by design, you may want to update the documentation to reflect.

**Comment by lanej0** [comment]
This is still a pending issue, but we've got it tracked internally.  I'm going to close it out here as it's not really a documentation problem but rather something that needs fixing up!
