### ISSUE TITLE
Invalid expense-category-id returns misleading error

### ISSUE THREAD

**Issue by jsirick** [harvesthq/api#86]
When making a post to /expenses , if the expense-category-id value is invalid, the following message is returned:

```
<?xml version="1.0" encoding="UTF-8"?>
<error>
    <kind>UserNotAssigned</kind>
    <message>Cannot create record as the User is not assigned to the requested project.</message>
</error>
```

**Comment by lanej0** [comment]
We've got an internal issue in our bug tracker for this, so I'm going to close this (as it relates to API documentation).
