### ISSUE TITLE
Add method to request all time entries in a specified period

### ISSUE THREAD

**Issue by svpino** [harvesthq/api#97]
My company relies on Harvest for all our operations. We use the API to load all the data to BigQuery and run reports that drive our business decisions.

Thanks for this API and for an amazing product!

That being said, one of our current pain points is while accessing our data we have to do multiple HTTP requests to retrieve all the time entries user by user. Right now we have 130 user accounts, so we have to issue 130 HTTP requests in order to keep our data updated with the Harvest information.

It would be nice if you guys add a method to retrieve all the time entries with only one HTTP request. Something like: /entries/#from/#till/. Of course, you'll have to be an admin in order for this method to succeed.

This will definitively add versatility to the API and will make our life way easier.

Thanks for considering this!

**Comment by lanej0** [comment]
Hi Santiago!

Thanks for requesting this.  Definitely not the first time I've seen this request, the biggest problem that we have with it is that it has a lot of potential to be abused.  It's a really expensive call to make.  Take your account for example:

130 people * 10 entries/day (I'm just picking a number here) * 5 working days a week * 4 weeks a month = 26,0000 entries returned in a single request.  And that's just a single month.  What if somebody decides to do a year's worth? We're looking at 312,000 entries in a single request....

So we could paginate the results, but you can't paginate the query against our database.

If somebody with ill intentions wants to mess with Harvest, they could start a trial account, import 1,000 users, import a bunch of time for each of those users and pretty much smoke our database server with a single request.  By splitting requests across people/projects, we have a way to limit the flow.

Hope that makes sense!

**Comment by svpino** [comment]
Thanks for your answer Jonathan!

Definitively makes sense, and I was afraid that was going to be your answer :) I think this is an important feature for the API but I understand the risk of opening up a real possibility of ill-intentioned calls.

I'm not going to pretend to know how you guys have structured your database in both the hardware and software fronts, but I'm sure you'll figure out eventually a way to make this happen while minimizing the risks. There are a bunch of ideas you can use, but they are highly dependent on the current setup you guys have. From caching, throttling, pagination on the database, etc, I hope you guys make this possible in the future.

Thanks

**Comment by adamlevenson** [comment]
I am faced with a similar issue as svpino, however I don't really care about the detail and rather want the totals. I find that we spend way too much time working around the reporting interface or having to do mass exports via CSV and pivot tables. I would rather just be able to access a "reporting" endpoint that would give me things like totals by date by client/project/user. I need to analyze all this data to see patterns in usage and budgets for our management dashboard and having to do an export or a ton of API calls makes me want to cry or find another platform.
