### ISSUE TITLE
GET /expenses is undocumented

### ISSUE THREAD

**Issue by bjornpost** [harvesthq/api#98]
Just noticed there is a `GET /expenses` API call to get all expenses in a period. It's not mentioned here: https://github.com/harvesthq/api/blob/master/Sections/Expense%20Tracking.md

Is it unsupported? Or just undocumented?

**Comment by lanej0** [comment]
I think you're probably talking about Expense Reporting: https://github.com/harvesthq/api/blob/master/Sections/Time%20and%20Expense%20Reporting.md?

**Comment by bjornpost** [comment]
No, the methods described over there require you to filter on either a `project_id` or a `user_id`. The mentioned `GET /expenses` returns all expenses:

    > GET https://example.harvestapp.com/expenses
    > Accept: application/xml
    > Accept-Encoding: gzip, deflate
    > Authorization: ...
    > Content-Type: application/xml
    > User-Agent: runscope/0.1

    > Status: 200 OK
    > <?xml version="1.0" encoding="UTF-8"?>
    > <expenses>
    >   <for_week_start_day type="date">2015-01-12</for_week_start_day>
    >   <for_week_end_day type="date">2015-01-18</for_week_end_day>
    > </expenses>

I'm just wondering if it's something that is supported but undocumented, or something that's unsupported and shouldn't be used.

**Comment by lanej0** [comment]
I don't know that I'd call this a bug -- it appears to just be defaulting to grabbing the expenses for the currently authenticated user for the current week.  That seems like a sensible default behavior for this.  That said, you're right, it's not documented.  So you're better to just pass the parameters as outlined here: https://github.com/harvesthq/api/blob/master/Sections/Time%20and%20Expense%20Reporting.md#get-all-expense-entries-logged-by-a-user-for-a-given-timeframe

**Comment by bjornpost** [comment]
Thanks!
